# Generated by Django 2.1.7 on 2020-04-02 11:03

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('course', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='name',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='course',
            name='short_description',
            field=models.TextField(default='ownerless'),
        ),
        migrations.AlterUniqueTogether(
            name='course',
            unique_together={('name', 's_year')},
        ),
        migrations.AlterUniqueTogether(
            name='joincourserequest',
            unique_together={('user', 'course')},
        ),
    ]
